import { StyleSheet } from 'react-native';

const commonStyles = StyleSheet.create({
  body: {
    margin: 0,
    color: '#777',
    fontSize: 15,
    fontFamily: 'Noto Sans KR',
  },
  page: {
    width: '100%',
    height: '100vh',
    backgroundColor: '#304A6E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  h1: {
    fontSize: 30,
    color: '#999',
  },
  hr: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e6e6e6',
  },
  hr2: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderStyle: 'dashed',
    marginVertical: 5,
  },
  input: {
    fontSize: 15,
    color: '#777',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    padding: 10,
    placeholderTextColor: '#b3b3b3',
  },
  inputFocus: {
    outline: 'none',
  },
  inputPlaceholder: {
    fontFamily: 'Noto Sans KR',
    color: '#b3b3b3',
  },
  button: {
    width: '100%',
    fontFamily: 'Noto Sans KR',
    fontSize: 19.2,
    fontWeight: 'bold',
    color: '#777',
    marginVertical: 0,
    backgroundColor: '#efefef',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    padding: 10,
    outline: 'none',
  },
  button2: {
    width: '100%',
    fontFamily: 'Noto Sans KR',
    fontSize: 16,
    color: '#999',
    backgroundColor: '#efefef',
    borderRadius: 10,
    padding: 10,
    outline: 'none',
  },
  link: {
    color: '#999',
    textDecorationLine: 'none',
  },
  jobAnnouncement: {
    textAlign: 'center',
  },
  interviewStartSection: {
    width: '100%',
    height: 80,
    backgroundColor: '#668DC0',
    position: 'absolute',
    bottom: 0,
    borderRadius: 25,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnGoInterview: {
    width: 90,
    height: 90,
    backgroundColor: '#668DC0',
    borderRadius: 45,
    marginBottom: 80,
  },
  interviewStartWord: {
    fontSize: 12.8,
    color: 'white',
    textAlign: 'center',
    position: 'absolute',
    bottom: 10,
  },
  modal: {
    position: 'absolute',
    zIndex: 10,
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  modalContent: {
    backgroundColor: '#fff',
    margin: 'auto',
    padding: 20,
    borderWidth: 1,
    borderColor: '#888',
    borderRadius: 10,
  },
  chatNoticeContent: {
    marginTop: 30,
    width: '70%',
  },
  chatNoticeButton: {
    width: '70%',
    margin: 'auto',
    fontFamily: 'Noto Sans KR',
    fontSize: 16,
    color: '#999',
    backgroundColor: '#efefef',
    borderRadius: 10,
    padding: 10,
    outline: 'none',
  },
  close: {
    color: '#aaa',
    fontSize: 28,
    fontWeight: 'bold',
  },
  closeHover: {
    color: 'black',
    textDecorationLine: 'none',
  },
});

export default commonStyles;